BEGIN;

-------------------
-- CREATE TABLES --
-------------------

CREATE TABLE IF NOT EXISTS "score"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "player_name" TEXT NOT NULL,
  "player_score" INTEGER,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ
);

-------------------
-- SEED --
-------------------

INSERT INTO "score" ("player_name", "player_score") VALUES
  ('Louise', 34),
  ('Camille', 37),
  ('Tom', 56),
  ('Cécile', 62),
  ('Maéva', 76);

COMMIT;