// Chargement du client PG
const { Client } = require('pg');

// Configuration d'une connexion
// const client = new Client({
//     host: process.env.PG_HOST,
//     user: process.env.PG_USER,
//     database: process.env.PG_DATABASE,
//     password: process.env.PG_PASSWORD
// });
const client = new Client(process.env.PG_URL);

// Connexion
client.connect(err => {
    if (err) {
        console.error('DataBase connection error', err.stack);
    } else {
        console.log('DataBase connection success');
    }
});

// deploy
const deployDb = async () => {
    const scores = await client.query(`
    BEGIN;

    CREATE TABLE IF NOT EXISTS "score"(
      "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      "player_name" TEXT NOT NULL,
      "player_score" INTEGER,
      "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "updated_at" TIMESTAMPTZ
    );

    DELETE FROM "score";

    INSERT INTO "score" ("player_name", "player_score") VALUES
      ('Louise', 169),
      ('Camille', 132),
      ('Tom', 148),
      ('Cécile', 175),
      ('Maéva', 198);
    
    COMMIT;
    `
    );
};

deployDb();

module.exports = client;